force-app/main/default/objects/Purchase_Order__c/Purchase_Order__c.object-meta.xml
<CustomObject>
    <description>A purchase order, often abbreviated to PO, is a commercial document issued by a buyer to a seller, indicating types, quantities, and agreed prices for products or services required. Purchase Orders are used to control the purchasing of products and services from external suppliers.</description>
    <label>Purchase Order</label>
    <nameField>
        <displayFormat>PO-{0000}</displayFormat>
        <label>PO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Purchase Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Purchase_Order__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>A short description of the goods or services being purchased.</description>
    <inlineHelpText>Enter a short description of the goods or services being purchased.</inlineHelpText>
    <label>Description</label>
    <required>true</required>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Total_Cost__c.field-meta.xml
<CustomField>
    <fullName>Total_Cost__c</fullName>
    <description>The total cost of the goods or services being purchased.</description>
    <inlineHelpText>Enter the total cost of the goods or services being purchased.</inlineHelpText>
    <label>Total Cost</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Purchase_Order__c/fields/Vendor__c.field-meta.xml
<CustomField>
    <fullName>Vendor__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>The vendor providing the goods, services, or subscriptions being purchased.</description>
    <inlineHelpText>Select the vendor from whom you&apos;re purchasing goods, services, or subscriptions.</inlineHelpText>
    <label>Vendor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Purchase Orders</relationshipLabel>
    <relationshipName>Purchase_Orders</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CreatePOController.cls
/**
 * CreatePOController
 */
public class CreatePOController {
    public String   searchString    {get; set;}
    public String   description     {get; set;}
    public Decimal  totalCost       {get; set;}
//    public List<SelectOption> selectedVendorIds {get; set;}
    public List<ApprovedVendor> approvedVendors {get; set;}
    public String selectedVendorId {get; set;}
    /**
     * Wrapper class for approved vendors
     */
    public class ApprovedVendor {
        public Account  acc         {get; set;}
        public Boolean  isSelected  {get; set;}
        public ApprovedVendor(Account a) {
            acc = a;
            isSelected = false;
        }
    }


    /**
     * Constructor
     */
    public CreatePOController() {
        approvedVendors = new List<ApprovedVendor>();
    }
    /**
     * Search for approved vendors
     */
    public void search() {
        if(String.isBlank(searchString) == false) {
            // Clear the approvedVendors list
            approvedVendors.clear();
            // Create a dynamic search string based on the user's input
            String searchStr = '%' + String.escapeSingleQuotes(searchString) + '%';
            // Use a SOQL for loop to wrap returned accounts as ApprovedVendor objects.
            for(Account a : [SELECT  Id, Name 
                             FROM    Account 
                             WHERE   Name LIKE :searchStr]) 
            {
                approvedVendors.add(new ApprovedVendor(a));
            }
        }
    }
    /**
     * Save the Purchase Order
     */
    public PageReference save() {

        if (selectedVendorId == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'You must select a vendor.'));
            return null;
        }

        Purchase_Order__c po = new Purchase_Order__c();
        po.Description__c = 'Test';
        po.Total_Cost__c = 1000;
//        po.Vendor__c = selectedVendorIds[0].getValue();
        po.Vendor__c = selectedVendorId;
        insert po;
        return null;
    }
}